<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ $title ?? 'Document' }}</title>
    <style>
        @page {
            margin: 0.75in;
        }
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            font-size: 12pt;
            line-height: 1.5;
            color: #333;
        }
        .header {
            margin-bottom: 1.5rem;
        }
        .name {
            font-size: 24pt;
            font-weight: bold;
            margin-bottom: 0.25rem;
        }
        .contact-info {
            font-size: 11pt;
            margin-bottom: 1rem;
        }
        .job-title {
            font-size: 16pt;
            font-weight: bold;
            margin-bottom: 0.25rem;
        }
        .company-name {
            font-size: 14pt;
            font-weight: bold;
            margin-bottom: 0.5rem;
        }
        .section-title {
            font-size: 14pt;
            font-weight: bold;
            border-bottom: 1pt solid #333;
            margin-top: 1rem;
            margin-bottom: 0.5rem;
        }
        .content {
            font-size: 12pt;
        }
        p {
            margin: 0.5rem 0;
        }
        ul {
            margin: 0.5rem 0;
            padding-left: 1.5rem;
        }
        li {
            margin-bottom: 0.25rem;
        }
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 9pt;
            font-style: italic;
            color: #777;
        }
    </style>
</head>
<body>
    @yield('content')
    
    <div class="footer">
        Generated by HireGlue on {{ date('F j, Y') }}
    </div>
</body>
</html>
